config/routes.rb
Rails.application.routes.draw do
  resources :my_blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_blog
end

app/models/my_blog.rb
class MyBlog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/my_blogs_controller.rb
class MyBlogsController < ApplicationController
  before_action :set_my_blog, only: [:show, :edit, :update, :destroy]

  # GET /my_blogs
  # GET /my_blogs.json
  def index
    @my_blogs = MyBlog.all
  end

  # GET /my_blogs/1
  # GET /my_blogs/1.json
  def show
  end

  # GET /my_blogs/new
  def new
    @my_blog = MyBlog.new
  end

  # GET /my_blogs/1/edit
  def edit
  end

  # POST /my_blogs
  # POST /my_blogs.json
  def create
    @my_blog = MyBlog.new(my_blog_params)

    respond_to do |format|
      if @my_blog.save
        format.html { redirect_to @my_blog, notice: 'My blog was successfully created.' }
        format.json { render :show, status: :created, location: @my_blog }
      else
        format.html { render :new }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_blogs/1
  # PATCH/PUT /my_blogs/1.json
  def update
    respond_to do |format|
      if @my_blog.update(my_blog_params)
        format.html { redirect_to @my_blog, notice: 'My blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_blog }
      else
        format.html { render :edit }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_blogs/1
  # DELETE /my_blogs/1.json
  def destroy
    @my_blog.destroy
    respond_to do |format|
      format.html { redirect_to my_blogs_url, notice: 'My blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_blog
      @my_blog = MyBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_blog_params
      params.require(:my_blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_blogs_helper.rb
module MyBlogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_blogs/_form.html.erb
<%= form_with(model: my_blog, local: true) do |form| %>
  <% if my_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_blog.errors.count, "error") %> prohibited this my_blog from being saved:</h2>

      <ul>
      <% my_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :my_blog_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :my_blog_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_blogs/edit.html.erb
<h1>Editing My Blog</h1>

<%= render 'form', my_blog: @my_blog %>

<%= link_to 'Show', @my_blog %> |
<%= link_to 'Back', my_blogs_path %>

app/views/my_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_blogs.each do |my_blog| %>
      <tr>
        <td><%= my_blog.title %></td>
        <td><%= my_blog.content %></td>
        <td><%= link_to 'Show', my_blog %></td>
        <td><%= link_to 'Edit', edit_my_blog_path(my_blog) %></td>
        <td><%= link_to 'Destroy', my_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Blog', new_my_blog_path %>

app/views/my_blogs/new.html.erb
<h1>New My Blog</h1>

<%= render 'form', my_blog: @my_blog %>

<%= link_to 'Back', my_blogs_path %>

app/views/my_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @my_blog.content %>
</p>

<%= link_to 'Edit', edit_my_blog_path(@my_blog) %> |
<%= link_to 'Back', my_blogs_path %>